### ISSUE TITLE
RC-10 change in behaviour

### ISSUE THREAD

**Issue by Goues** [woltapp/redux-autoloader#3]
Hello again,

we are currently using RC-9 in production and upon trying RC-11, we have found a regression bug. It might not really be a bug, since you said that RC-10:

> fixed incorrect behavior when loader has been initialized and reloadOnMount=false

We have a following setup with reloadOnMount false because we have multiple independent components using the same loader:

```
{
reloadOnMount: false,
cacheExpiresIn: 15e3,
autoRefreshInterval: 60e3
}
```

When using the default of true, two component in the same loader triggered two identical network requests and a lot of other requests on component updates.

The change in RC-10 is that the apiCall is not triggered on first mount at all (I expected it would, because loadOnInitialize is still true), but it doesn't. It only triggers API for the first time after 60 seconds (the first refresh interval).

Is that expected or are we just using it wrong?

**Comment by nygardk** [comment]
Thanks for reporting this! I will investigate the problem.

**Comment by nygardk** [comment]
Please try if version `1.0.0-rc.13` fixed this issue!

**Comment by Goues** [comment]
Hi, sorry for the delay but I finally got to test this and I confirm it is now working as expected. Thank you.
